name: gmail_settings_ui
#Appini Akhil
#PES1UG20CS074
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  dropdown_button2:
  flutter:
    sdk: flutter
  html_editor_enhanced:
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: TiltPrism
      fonts:
        - asset: assets/fonts/TiltPrism-Regular.ttf
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf
